#!/usr/bin/env ruby

require 'capybara'
require 'date'
require 'fileutils'
require 'dotenv'
Dotenv.load

PAL_USER_ID = ENV['PAL_USER_ID']
PAL_PASSWORD = ENV['PAL_PASSWORD']
DELI_USER_ID = ENV['DELI_USER_ID']
DELI_PASSWORD = ENV['DELI_PASSWORD']

def write_html(session, filename)
  FileUtils.mkdir_p('tmp')
  IO.write(filename, session.html)
end

def pal_system
  session = Capybara::Session.new(:selenium_chrome)
  session.visit 'https://shop.pal-system.co.jp/ipsc/restTermEntry.htm'
  session.fill_in 'loginId', with: PAL_USER_ID
  session.fill_in 'password', with: PAL_PASSWORD
  session.find('.send input[type="image"]').click

  # 配達回と配達日の対応を取得
  # お休みの申し込みなら配達日が表示される。でも未来しか見えない。
  # session.visit 'https://shop.pal-system.co.jp/ipsc/restTermEntry.htm'
  session.find(:xpath, "//a[contains(., 'お休みを申し込む')]").click
  session.assert_text 'ご注文のお休みを開始する企画回'

  today = Date.today
  delivery_days = session.all('.list-input.orderRest .col.title').map do |node|
    # 1月4回　2月2日(金)お届け商品分
    if m = /\A((\d+)月\S+) (\d+)月(\d+)日/.match(node.text)
      name_month = m[2].to_i
      name_year = today.month <= name_month ? today.year : today.year + 1
      month = m[3].to_i
      day = m[4].to_i
      date = Date.new(today.month <= month ? today.year : today.year + 1, month, day)
      { year: name_year, name: m[1], delivery_date: date }
    else
      raise "#{node.text} does not match!"
    end
  end
  puts delivery_days

  # 注文
  session.visit 'https://shop.pal-system.co.jp/pal/OrderReferenceDirect.do'
  session.assert_text '注文履歴'

  write_html(session, 'tmp/pal.html')

  doc = Nokogiri::HTML.parse(session.html)
  puts doc.xpath("//div[@class='section record']/h2").text.gsub(/\s+/, ' ')
  items = doc.xpath("//table[contains(@class,'order-table1')]/tbody/tr[td[contains(@class,'item')]]").map do |node|
    {
      name: node.xpath("td[contains(@class,'item')]").text.gsub(/\s+/, ' '),
      quantity: node.xpath("td[@class='quantity']").text.gsub(/\s+/, ''),
      price: node.xpath("td[@class='price']").text.gsub(/\s+/, ''),
      total: node.xpath("td[@class='total']").text.gsub(/\s+/, ''),
    }
  end
  puts items
end

def coop_deli
  session = Capybara::Session.new(:selenium_chrome)
  session.visit 'https://weekly.coopdeli.jp/order/index.html'

  # fill_in だとなぜか組合員コードが1桁抜けて入力されてしまうので、javascriptで入力する
  # session.fill_in 'j_username', with: '2434126268'
  session.execute_script %(document.querySelector('input[name="j_username"]').value = '#{DELI_USER_ID}')
  session.fill_in 'j_password', with: DELI_PASSWORD
  session.find('.FW_submitLink').click

  # 週選択
  osk_options = session.all('select[name="osk"] option')
  osks = osk_options.map { |node| node['value'] }
  odc = session.find('input[name="curodc"]', visible: false).value

  # window = session.window_opened_by do
  #   session.click_link '印刷画面へ'
  # end
  # session.switch_to_window window

  osk = osks.first
  osks.first(3).each do |osk|
    unless m = /\A(\d{4})(\d{2})(\d{2})\z/.match(osk)
      raise "osk mismatch: #{osk}"
    end
    name_year = m[1].to_i
    name_month = m[2].to_i
    name_time = m[3].to_i
    # "2018年１月５回" のような文字列で印刷ページがひらいたことを確認
    dalivery_name = "#{m[1]}年" + "#{m[2].to_i}月#{m[3].to_i}回".tr('0-9', '０-９')
    session.visit "https://weekly.coopdeli.jp/order/print.html?osk=#{osk}&odc=#{odc}"
    session.assert_title '注文確認（印刷用）｜ウイークリーコープ'
    session.assert_text dalivery_name

    write_html(session, 'tmp/deli.html')

    doc = Nokogiri::HTML.parse(session.html)
    date = doc.xpath("//div[@class='cartWeekOrder']/dl/dd[1]").text
    items = doc.xpath("//tr[not(@class) and td[@class='cartItemDetail']]").map do |node|
      {
        name: node.xpath("td[@class='cartItemDetail']/p").text,
        quantity: node.xpath("td[@class='cartItemQty']").text,
        price: node.xpath("td[@class='cartItemLot']").text,
        total: node.xpath("td[@class='cartItemPrice']").text,
      }
    end
    puts "***** #{name_year}年#{name_month}月#{name_time}回: #{date}"
    puts items
  end
end

puts '************************************* COOP DELI'
coop_deli
puts '************************************* PAL SYSTEM'
pal_system
